# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import university_pb2 as university__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in university_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BookServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListBooks = channel.unary_stream(
                '/university.BookService/ListBooks',
                request_serializer=university__pb2.Empty.SerializeToString,
                response_deserializer=university__pb2.Book.FromString,
                _registered_method=True)
        self.GetBook = channel.unary_unary(
                '/university.BookService/GetBook',
                request_serializer=university__pb2.IdRequest.SerializeToString,
                response_deserializer=university__pb2.Book.FromString,
                _registered_method=True)
        self.AddBook = channel.unary_unary(
                '/university.BookService/AddBook',
                request_serializer=university__pb2.Book.SerializeToString,
                response_deserializer=university__pb2.Book.FromString,
                _registered_method=True)
        self.UpdateBook = channel.unary_unary(
                '/university.BookService/UpdateBook',
                request_serializer=university__pb2.Book.SerializeToString,
                response_deserializer=university__pb2.Book.FromString,
                _registered_method=True)
        self.DeleteBook = channel.unary_unary(
                '/university.BookService/DeleteBook',
                request_serializer=university__pb2.IdRequest.SerializeToString,
                response_deserializer=university__pb2.Empty.FromString,
                _registered_method=True)


class BookServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListBooks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BookServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListBooks': grpc.unary_stream_rpc_method_handler(
                    servicer.ListBooks,
                    request_deserializer=university__pb2.Empty.FromString,
                    response_serializer=university__pb2.Book.SerializeToString,
            ),
            'GetBook': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBook,
                    request_deserializer=university__pb2.IdRequest.FromString,
                    response_serializer=university__pb2.Book.SerializeToString,
            ),
            'AddBook': grpc.unary_unary_rpc_method_handler(
                    servicer.AddBook,
                    request_deserializer=university__pb2.Book.FromString,
                    response_serializer=university__pb2.Book.SerializeToString,
            ),
            'UpdateBook': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateBook,
                    request_deserializer=university__pb2.Book.FromString,
                    response_serializer=university__pb2.Book.SerializeToString,
            ),
            'DeleteBook': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteBook,
                    request_deserializer=university__pb2.IdRequest.FromString,
                    response_serializer=university__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'university.BookService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('university.BookService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BookService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListBooks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/university.BookService/ListBooks',
            university__pb2.Empty.SerializeToString,
            university__pb2.Book.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/university.BookService/GetBook',
            university__pb2.IdRequest.SerializeToString,
            university__pb2.Book.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/university.BookService/AddBook',
            university__pb2.Book.SerializeToString,
            university__pb2.Book.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/university.BookService/UpdateBook',
            university__pb2.Book.SerializeToString,
            university__pb2.Book.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/university.BookService/DeleteBook',
            university__pb2.IdRequest.SerializeToString,
            university__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class StudentServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListStudents = channel.unary_stream(
                '/university.StudentService/ListStudents',
                request_serializer=university__pb2.Empty.SerializeToString,
                response_deserializer=university__pb2.Student.FromString,
                _registered_method=True)
        self.GetStudent = channel.unary_unary(
                '/university.StudentService/GetStudent',
                request_serializer=university__pb2.IdRequest.SerializeToString,
                response_deserializer=university__pb2.Student.FromString,
                _registered_method=True)
        self.AddStudent = channel.unary_unary(
                '/university.StudentService/AddStudent',
                request_serializer=university__pb2.Student.SerializeToString,
                response_deserializer=university__pb2.Student.FromString,
                _registered_method=True)
        self.UpdateStudent = channel.unary_unary(
                '/university.StudentService/UpdateStudent',
                request_serializer=university__pb2.Student.SerializeToString,
                response_deserializer=university__pb2.Student.FromString,
                _registered_method=True)
        self.DeleteStudent = channel.unary_unary(
                '/university.StudentService/DeleteStudent',
                request_serializer=university__pb2.IdRequest.SerializeToString,
                response_deserializer=university__pb2.Empty.FromString,
                _registered_method=True)


class StudentServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListStudents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStudent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddStudent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateStudent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteStudent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StudentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListStudents': grpc.unary_stream_rpc_method_handler(
                    servicer.ListStudents,
                    request_deserializer=university__pb2.Empty.FromString,
                    response_serializer=university__pb2.Student.SerializeToString,
            ),
            'GetStudent': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStudent,
                    request_deserializer=university__pb2.IdRequest.FromString,
                    response_serializer=university__pb2.Student.SerializeToString,
            ),
            'AddStudent': grpc.unary_unary_rpc_method_handler(
                    servicer.AddStudent,
                    request_deserializer=university__pb2.Student.FromString,
                    response_serializer=university__pb2.Student.SerializeToString,
            ),
            'UpdateStudent': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateStudent,
                    request_deserializer=university__pb2.Student.FromString,
                    response_serializer=university__pb2.Student.SerializeToString,
            ),
            'DeleteStudent': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteStudent,
                    request_deserializer=university__pb2.IdRequest.FromString,
                    response_serializer=university__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'university.StudentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('university.StudentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StudentService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListStudents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/university.StudentService/ListStudents',
            university__pb2.Empty.SerializeToString,
            university__pb2.Student.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStudent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/university.StudentService/GetStudent',
            university__pb2.IdRequest.SerializeToString,
            university__pb2.Student.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddStudent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/university.StudentService/AddStudent',
            university__pb2.Student.SerializeToString,
            university__pb2.Student.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateStudent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/university.StudentService/UpdateStudent',
            university__pb2.Student.SerializeToString,
            university__pb2.Student.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteStudent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/university.StudentService/DeleteStudent',
            university__pb2.IdRequest.SerializeToString,
            university__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class LoanServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListLoans = channel.unary_stream(
                '/university.LoanService/ListLoans',
                request_serializer=university__pb2.Empty.SerializeToString,
                response_deserializer=university__pb2.Loan.FromString,
                _registered_method=True)
        self.GetLoan = channel.unary_unary(
                '/university.LoanService/GetLoan',
                request_serializer=university__pb2.IdRequest.SerializeToString,
                response_deserializer=university__pb2.Loan.FromString,
                _registered_method=True)
        self.AddLoan = channel.unary_unary(
                '/university.LoanService/AddLoan',
                request_serializer=university__pb2.Loan.SerializeToString,
                response_deserializer=university__pb2.Loan.FromString,
                _registered_method=True)
        self.ReturnLoan = channel.unary_unary(
                '/university.LoanService/ReturnLoan',
                request_serializer=university__pb2.IdRequest.SerializeToString,
                response_deserializer=university__pb2.Loan.FromString,
                _registered_method=True)


class LoanServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListLoans(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLoan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddLoan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReturnLoan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LoanServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListLoans': grpc.unary_stream_rpc_method_handler(
                    servicer.ListLoans,
                    request_deserializer=university__pb2.Empty.FromString,
                    response_serializer=university__pb2.Loan.SerializeToString,
            ),
            'GetLoan': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLoan,
                    request_deserializer=university__pb2.IdRequest.FromString,
                    response_serializer=university__pb2.Loan.SerializeToString,
            ),
            'AddLoan': grpc.unary_unary_rpc_method_handler(
                    servicer.AddLoan,
                    request_deserializer=university__pb2.Loan.FromString,
                    response_serializer=university__pb2.Loan.SerializeToString,
            ),
            'ReturnLoan': grpc.unary_unary_rpc_method_handler(
                    servicer.ReturnLoan,
                    request_deserializer=university__pb2.IdRequest.FromString,
                    response_serializer=university__pb2.Loan.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'university.LoanService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('university.LoanService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LoanService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListLoans(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/university.LoanService/ListLoans',
            university__pb2.Empty.SerializeToString,
            university__pb2.Loan.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLoan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/university.LoanService/GetLoan',
            university__pb2.IdRequest.SerializeToString,
            university__pb2.Loan.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddLoan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/university.LoanService/AddLoan',
            university__pb2.Loan.SerializeToString,
            university__pb2.Loan.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReturnLoan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/university.LoanService/ReturnLoan',
            university__pb2.IdRequest.SerializeToString,
            university__pb2.Loan.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
